print("****** OPÇÕES ******")
print("1- Opção 1")
print("2- Opção 2")
print("3- Opção 3")
print("4- Opção 4")
print("5- SAIR")
opcao=str.upper(input("Escolha a opção: "))
while opcao != "SAIR":
    input("Aperte ENTER para continuar:")
    print("****** OPÇÕES ******")
    print("1- Opção 1")
    print("2- Opção 2")
    print("3- Opção 3")
    print("4- Opção 4")
    print("5- SAIR")
    opcao=str.upper(input("Escolha a opção: "))